version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo installing sam 
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "installing npm packages on hello-world"
      - cd hello-world && npm install && cd -
     
  build:
    commands:
      - echo build started at `date` for environemnt $ENV_NAME
      #- sam build && sam package --s3-bucket janahitha-lambda-dev --output-template-file sam-template.yaml
      #- sam package --template-file template.yaml --s3-bucket janahitha-lambda-dev --output-template-file sam-template.yaml
      - aws cloudformation package --template-file template.yaml --s3-bucket janahitha-lambda-dev --output-template-file sam-template.yaml
  post_build:
    commands:
      - echo deployment completed at `date`

artifacts:
  type: zip
  files:
    - sam-template.yaml
